/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inter;

/**
 *
 * @author josep
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cantidad_Mesas = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("Cantidad de mesas:");
        add(jLabel1);
        jLabel1.setBounds(64, 94, 95, 14);
        add(cantidad_Mesas);
        cantidad_Mesas.setBounds(169, 90, 70, 20);

        aceptar.setText("Aceptar");
        add(aceptar);
        aceptar.setBounds(160, 230, 71, 23);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField cantidad_Mesas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
