/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces_administrador;

import java.text.MessageFormat;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josep
 */
public class Informe_Inventario extends javax.swing.JPanel {

    DefaultTableModel model;
    Timer time;
    TimerTask timerTask;

    /**
     * Creates new form Informe_Inventario
     */
    public Informe_Inventario() {
        initComponents();
        iniciar_tabla();
        incertarFila();
        timerTask = new TimerTask() {
            @Override
            public void run() {
                iniciar_tabla();
                incertarFila();
            }
        };
        
        time=new Timer();
        time.scheduleAtFixedRate(timerTask, 10000, 10000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_inventario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        generar_pdf = new javax.swing.JButton();

        tabla_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_inventario);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/almacen.jpg"))); // NOI18N

        generar_pdf.setText("imprimir");
        generar_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generar_pdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(generar_pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(generar_pdf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generar_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generar_pdfActionPerformed
        MessageFormat Header = new MessageFormat("Menu");
        MessageFormat footer = new MessageFormat("Page[0,number,integer]");
        try {
            tabla_inventario.print(JTable.PrintMode.NORMAL, Header, footer);
        } catch (java.awt.print.PrinterException ex) {
            System.out.println("Error al crear el archivo. " + ex);
        }
    }//GEN-LAST:event_generar_pdfActionPerformed

    private void iniciar_tabla() {
        model = new DefaultTableModel();
        model.addColumn("Mesa");
        model.addColumn("Plato");
        model.addColumn("Añadio");
        model.addColumn("Quito");
        tabla_inventario.setModel(model);
    }

    private void incertarFila() {
        for (codigo.pedidos carga : codigo.archivoAdiciones.adiciones) {
            String[] agregar = new String[4];
            agregar[0] = String.valueOf(carga.getNumMesas());
            agregar[1] = carga.getPlato();
            agregar[2] = carga.getAñadirPorcion();
            agregar[3] = carga.getQuitarPotcion();
            model.addRow(agregar);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generar_pdf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_inventario;
    // End of variables declaration//GEN-END:variables
}
