/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces_administrador;

import codigo.datosMesero;
import codigo.pedido;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josep
 */
public class Informe_modos_de_pago extends javax.swing.JPanel {
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form Informe_modos_de_pago
     */
    public Informe_modos_de_pago() {
        initComponents();
        iniciar_tabla();
        llenar_tabla();
    }
    
    public int numero_mesa;

    byte cont;
    interfaces_caja.verPedido obt;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Pagos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        generar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabla_Pagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_Pagos);

        jLabel1.setText("Total:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pagos.png"))); // NOI18N

        generar.setText("Generar PDF");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(generar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
       MessageFormat Header = new MessageFormat("Menu");
        MessageFormat footer = new MessageFormat("Page[0,number,integer]");
        //String valores=llenar_tabla();
        try { 
            tabla_Pagos.print(JTable.PrintMode.NORMAL,Header,footer);
        } catch (java.awt.print.PrinterException ex) {
            System.out.println("Error al crear el archivo.");
        }
    }//GEN-LAST:event_generarActionPerformed
    
    private void iniciar_tabla(){
        model.addColumn("Mesa");
        model.addColumn("Efectivo");
        model.addColumn("Débito");
        model.addColumn("Crédito");
        tabla_Pagos.setModel(model);
    }
    
    private void llenar_tabla(){
        codigo.archivoPedido.busqueda(numero_mesa);
        File archivo_lector;
        FileReader lector = null;
        BufferedReader linea;
        try {
            int retorno;

            archivo_lector = new File("src/ficheros/Precios efectivo.txt");
            lector = new FileReader(archivo_lector);
            linea = new BufferedReader(lector);
            String cadena;
            String tipo_de_pago;
            while((cadena=linea.readLine()) != null){ //recorre todo el archivo
                String dato[] = cadena.split(";");
                retorno=Integer.parseInt(dato[0]);
                tipo_de_pago=dato[1];
                if("Efectivo".equals(tipo_de_pago)){
                    int contador = 0;
                    for (pedido object : codigo.archivoPedido.lista) {
                        model.addRow(dato);
                        model.setValueAt(numero_mesa, contador, 0);
                        model.setValueAt(retorno, contador, 1);
                        model.setValueAt(0, contador, 2);
                        model.setValueAt(0, contador, 3);
                        tabla_Pagos.setModel(model);
                    }
                }else{
                    if("Debito".equals(tipo_de_pago)){
                        int contador = 0;
                        for (pedido object : codigo.archivoPedido.lista) {
                            model.insertRow(contador, new Object[]{});
                            model.setValueAt(numero_mesa, contador, 0);
                            model.setValueAt(0, contador, 1);
                            model.setValueAt(retorno, contador, 2);
                            model.setValueAt(0, contador, 3);
                            tabla_Pagos.setModel(model);
                        }
                    }else{
                        int contador = 0;
                        for (pedido object : codigo.archivoPedido.lista) {
                            model.insertRow(contador, new Object[]{});
                            model.setValueAt(numero_mesa, contador, 0);
                            model.setValueAt(0, contador, 1);
                            model.setValueAt(0, contador, 2);
                            model.setValueAt(retorno, contador, 3);
                            tabla_Pagos.setModel(model);
                        }
                    }
                }
            }
        } catch (IOException | NumberFormatException e) {
            System.out.println("Error abriendo/leyendo el archivo "+e);
        }finally{
            try {
                if (lector!=null) {
                    lector.close();
                } else {
                }
            } catch (IOException e) {
                System.out.println("Error cerrando el archivo "+e);
            }
        }
        
    }
    
    private void incertarColunas() {
        
        model.addColumn("Dia");/*
        for (cargarCombos object : codigo.archivoPlatos.mostrarPlato) {
            model.addColumn(object.getNombre());
            System.out.println(object);
        
        }
        */
        tabla_Pagos.setModel(model);
    }

    private void incertarFila() {
        for (datosMesero carga : codigo.listaMeseros.meseros) {
            String[] agregar=new String[3];
            agregar[0]=String.valueOf(carga.getCodigo());
            agregar[1]=carga.getNombre();
            agregar[2]=carga.getApellido();
            model.addRow(agregar);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tabla_Pagos;
    // End of variables declaration//GEN-END:variables
}
