/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces_administrador;

import java.io.File;

/**
 *
 * @author josep
 */
public class mesas extends javax.swing.JPanel {
    public static int num_mesas;
    /**
     * Creates new form NewJPanel
     */
    public mesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cantidad_Mesas = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        jLabel1.setText("Cantidad de mesas:");
        add(jLabel1);
        jLabel1.setBounds(20, 90, 130, 20);

        cantidad_Mesas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidad_MesasKeyTyped(evt);
            }
        });
        add(cantidad_Mesas);
        cantidad_Mesas.setBounds(150, 80, 230, 30);

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        add(aceptar);
        aceptar.setBounds(80, 160, 200, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesa.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(230, 70, 590, 310);
    }// </editor-fold>//GEN-END:initComponents
    
    File file =new File ("src/ficheros/mesas.txt");
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        String numero=null;
        num_mesas=Integer.parseInt(cantidad_Mesas.getText());
        if(file.exists()){
            codigo.archivoGeneral.archivoCrear(num_mesas);
        }else{
            codigo.archivoGeneral.crear(num_mesas);
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void cantidad_MesasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad_MesasKeyTyped
        char c =evt.getKeyChar();
        if (c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_cantidad_MesasKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField cantidad_Mesas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
