/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces_administrador;

/**
 *
 * @author Eduardo Jimenez
 */
public class meseros extends javax.swing.JPanel {
public static int codi_mesero;
public static String nom_mesero;
    /**
     * Creates new form meseros
     */
    public meseros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre_mesero = new javax.swing.JTextField();
        aceptar_meseros = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigo_mesero = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setText("Nombre del mesero");
        add(jLabel1);
        jLabel1.setBounds(10, 50, 170, 30);

        nombre_mesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_meseroActionPerformed(evt);
            }
        });
        add(nombre_mesero);
        nombre_mesero.setBounds(130, 50, 140, 30);

        aceptar_meseros.setText("aceptar");
        add(aceptar_meseros);
        aceptar_meseros.setBounds(40, 180, 150, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/meseros-1.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(340, 10, 470, 390);

        jLabel2.setText("Codigo");
        add(jLabel2);
        jLabel2.setBounds(20, 130, 160, 14);
        add(codigo_mesero);
        codigo_mesero.setBounds(130, 110, 140, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_meseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_meseroActionPerformed
        // TODO add your handling code here:
        String numero=null;
        String nombre=null;
        codi_mesero=Integer.parseInt(codigo_mesero.getText());
        nom_mesero=(nombre_mesero.getText());
    }//GEN-LAST:event_nombre_meseroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar_meseros;
    private javax.swing.JTextField codigo_mesero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombre_mesero;
    // End of variables declaration//GEN-END:variables
}
