/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces_administrador;

/**
 *
 * @author Juan Diego Pachón
 */
public class platos extends javax.swing.JPanel {

    /**
     * Creates new form platos
     */
    public platos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        comidas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ingredientes = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        labelNombre.setText("Nombre del plato");
        jPanel1.add(labelNombre);
        labelNombre.setBounds(30, 110, 200, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 130, 230, 50);

        jLabel2.setText("Precio");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 110, 69, 14);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(350, 130, 167, 50);

        comidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Almuerzo", "Cena", "Postres", "Bebidas" }));
        comidas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comidasItemStateChanged(evt);
            }
        });
        comidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comidasActionPerformed(evt);
            }
        });
        jPanel1.add(comidas);
        comidas.setBounds(13, 47, 182, 33);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingredientes");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 190, 106, 47);

        ingredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientesActionPerformed(evt);
            }
        });
        jPanel1.add(ingredientes);
        ingredientes.setBounds(30, 230, 230, 47);

        agregar.setText("Agregar");
        jPanel1.add(agregar);
        agregar.setBounds(70, 300, 120, 23);

        jButton2.setText("Aceptar");
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 360, 139, 43);

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Comidas");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(285, 11, 133, 63);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ingredientes.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 200, 220, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void comidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comidasActionPerformed

    private void ingredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredientesActionPerformed

    private void comidasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comidasItemStateChanged
        if (comidas.getSelectedItem()=="Bebidas"|| comidas.getSelectedItem()=="Postres"){
            ingredientes.setEnabled(false);
            agregar.setEnabled(false);
            labelNombre.setText("Nombre");
        }else{
            ingredientes.setEnabled(true);
            agregar.setEnabled(true);
            labelNombre.setText("Nombre del plato");
        }
    }//GEN-LAST:event_comidasItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JComboBox<String> comidas;
    private javax.swing.JTextField ingredientes;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables
}
